HW2 is completed
MaxFando/hw-otus pull request #2
Opened 2023-06-18 15:43 UTC by MaxFando

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-06-19 03:57 UTC, vladislavmass requested changes
Отличное начало. Код отлично работает с символами ASCII, но вот с юникодом он работать не может. Причина этого что оператор `[]` применительно к строке с многобайтовой кодировкой адресует не символ, а конкретный байт. Тест кейс для проверки `{input: "aaв2a0b", expected: "aaввb"}`. Также  неверное имя модуля в ` go.mod`.

2023-06-19 03:57 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	slowPtr := 0
Непонятно имя переменной `медленный указатель`

2023-06-19 03:57 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	fastPtr := 0
Непонятно имя переменной `быстрый указатель`

2023-06-20 17:49 UTC, vladislavmass requested changes
Круто что код начал работать с unicode. В коде все еще есть ошибка, для ее выявления можно использовать ошибочный тест кейс `"aaa15b"`.  Для выявления ошибок рекомендую писать больше тестов. 

Также хочу напомнить что имя модуля это путь до него на гитхабе. В данном случае это `github.com/MaxFando/hw-otus/hw02_unpack_string`

2023-06-20 17:49 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	fastPtrIndex := 0
Непонятно причем тут быстро и медленно в именах переменных

2023-06-20 17:49 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	if runeSlice[fastPtrIndex] == '0' && runeSlice[slowPtrIndex] == '0' {
`fastPtrIndex==fastPtrIndex==0` .Непонятно в чем смысл этих 2 проверок, может стоит оставить 1?

2023-06-21 02:14 UTC, MaxFando commented on hw02_unpack_string/unpack.go
> +	fastPtrIndex := 0
Алгоритмический патерн, быстрый и медленный указатель
https://codeburst.io/fast-and-slow-pointer-floyds-cycle-detection-algorithm-9c7a8693f491

В первую очередь я двигаю fastPtrIndex, он является у меня лидером, при этом slowPtrIndex стоит на месте и ждет команды когда ему начать двигаться

во всех примерах этого паттерна  я видел именования именно fast, slow

2023-06-21 04:35 UTC, vladislavmass requested changes
Старый баг ушел, но появился новый. Для его поиска рекомендую использовать тест кейс `{input: `qwe\40ф`, expected: `qweф`},`

2023-06-21 04:35 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		case unicode.IsDigit(runeSlice[fastPtrIndex]) && runeSlice[fastPtrIndex] != '0':
Разница между кодом с 29 по 42 и кодом между 43 и 53 всего 3 строчки. Может стоит их объединить в 1 case и внутри него уже принимать решение на счет этих нескольких команд с помощью if?

2023-06-21 04:35 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +			for slowPtrIndex < fastPtrIndex-1 {
Данный цикл в коде в одном и том же виде повторяется 4 раза. Предлагаю что-то с этим сделать. Либо можно попробовать найти для него общее место. либо вынести в отдельную функцию.

2023-06-21 04:35 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	fastPtrIndex := 0
В данном случае он делает только хуже. С помощью этого алгоритма получается ситуация когда происходит копирование в 16 строке, так как требуется возможность адресации элемента в строке. Есть основной цикл и есть цикл работающий со slow. Это не является ошибкой, это просто рекомендация.

2023-06-25 09:16 UTC, vladislavmass approved these changes
Работа принята. Оценка 8/10. -2 бала за множественное дублирование кода.

2023-07-16 10:02 UTC, merged